### ISSUE TITLE
总是报  SyntaxError: Unexpected number 这个错误 

### ISSUE THREAD

**Issue by franckXu** [JacksonTian/sync_package#12]
总是报这个错误，就结束，为什么会报这个错？
------------------------------
undefined:1
--034c17c2048599c2b1419d41db75d98b
 ^
SyntaxError: Unexpected number
    at Object.parse (native)
    at Request._callback (d:\node\node-global\node_modules\sync_package\lib\sync_package.js:95:49)
    at Request.self.callback (d:\node\node-global\node_modules\sync_package\node_modules\request\request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (d:\node\node-global\node_modules\sync_package\node_modules\request\request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (d:\node\node-global\node_modules\sync_package\node_modules\request\request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by JacksonTian** [comment]
用cnpm吧

发自我的 iPhone

**Comment by JacksonTian** [comment]
现在有更好的方式，参见 cnpm
